### ISSUE TITLE
Add calendar event reminders to iCal feed

### ISSUE THREAD

**Issue by LarsSelbekk** [mathiazom/rezervo#18]
Currently, there's an option to be reminded by rezervo, but it's using a custom solution. It would be helpful to also set that as the default reminder time in the iCal-feed, to get a proper notification by your default calendar app. There's an override setting for it in Google Calendar, but not in Outlook. I don't really need there to be a separate setting in rezervo-web for the iCal-reminders, but it would be nice.

Workaround if added via Google Calendar, which doesn't exist in Outlook:
![image](https://github.com/mathiazom/rezervo/assets/6224384/b91c7d81-56b1-48bb-9724-54681b578086)

**Comment by mathiazom** [comment]
See https://github.com/mathiazom/rezervo/pull/30
